<a href="https://colab.research.google.com/github/leviaaf/KNN_SVM_IoTFireDetection_AccuracyTesting/blob/main/SVM_IoTFireDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv('Training Dataset.csv')

In [3]:
dataset.head()

Time  Api  Suhu  Kelembaban    PPM            Label
0  13:33:59    0  26.9          72  50.14  Tidak Kebakaran
1  13:34:03    0  26.8          72  50.89  Tidak Kebakaran
2  13:34:06    0  26.9          72  49.77  Tidak Kebakaran
3  13:34:10    0  26.9          72  51.64  Tidak Kebakaran
4  13:34:14    0  26.8          72  54.34  Tidak Kebakaran

In [4]:
le=LabelEncoder()
dataset["Label"]=le.fit_transform(dataset["Label"])

In [5]:
dataset.head()

Time  Api  Suhu  Kelembaban    PPM  Label
0  13:33:59    0  26.9          72  50.14      0
1  13:34:03    0  26.8          72  50.89      0
2  13:34:06    0  26.9          72  49.77      0
3  13:34:10    0  26.9          72  51.64      0
4  13:34:14    0  26.8          72  54.34      0

In [6]:
dataset = dataset.iloc[:,1:]
dataset.head()

Api  Suhu  Kelembaban    PPM  Label
0    0  26.9          72  50.14      0
1    0  26.8          72  50.89      0
2    0  26.9          72  49.77      0
3    0  26.9          72  51.64      0
4    0  26.8          72  54.34      0

In [7]:
x=dataset.iloc[ : , :-1]
x.head()

Api  Suhu  Kelembaban    PPM
0    0  26.9          72  50.14
1    0  26.8          72  50.89
2    0  26.9          72  49.77
3    0  26.9          72  51.64
4    0  26.8          72  54.34

In [8]:
y=dataset.iloc[ : ,-1]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Label, dtype: int64

In [9]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [10]:
print(xtrain)

     Api  Suhu  Kelembaban      PPM
269    0  23.3          84     8.58
109    1  35.1          84  2748.92
50     0  26.8          75    62.54
202    1  30.1          73   323.20
135    0  23.6          85    56.72
..   ...   ...         ...      ...
56     0  26.8          75    59.59
194    1  26.6          82   464.86
27     0  26.8          74    49.03
325    1  36.9          46   599.33
5      0  26.8          72    47.57

[296 rows x 4 columns]


In [11]:
print(xtest)

     Api  Suhu  Kelembaban      PPM
140    0  23.6          84    48.66
172    0  23.6          85    60.84
257    0  23.2          84     4.99
117    1  39.4          77  3724.66
54     0  26.8          75    50.89
..   ...   ...         ...      ...
332    0  35.7          45   621.83
312    1  25.1          85  9053.61
217    1  34.4          63   393.85
231    1  37.0          55   421.24
87     1  28.0          76   441.85

[75 rows x 4 columns]


In [12]:
from sklearn.preprocessing import Normalizer
normscaler = Normalizer()
xtrain = normscaler.fit_transform(xtrain)
xtest = normscaler.fit_transform(xtest)

In [13]:
print(xtrain)

[[0.00000000e+00 2.66003463e-01 9.58982443e-01 9.79532067e-02]
 [3.63579874e-04 1.27616536e-02 3.05407094e-02 9.99451986e-01]
 [0.00000000e+00 2.64653552e-01 7.40634940e-01 6.17590789e-01]
 ...
 [0.00000000e+00 2.89022401e-01 7.98046929e-01 5.28760012e-01]
 [1.66050870e-03 6.12727710e-02 7.63834001e-02 9.95192678e-01]
 [0.00000000e+00 2.96587502e-01 7.96802244e-01 5.26442816e-01]]


In [14]:
print(xtest)

[[0.00000000e+00 2.36227412e-01 8.40809433e-01 4.87068893e-01]
 [0.00000000e+00 2.20229512e-01 7.93199513e-01 5.67744216e-01]
 [0.00000000e+00 2.65787777e-01 9.62335055e-01 5.71672848e-02]
 [2.68408509e-04 1.05752953e-02 2.06674552e-02 9.99730437e-01]
 [0.00000000e+00 2.83553718e-01 7.93527197e-01 5.38434654e-01]
 [0.00000000e+00 2.63541128e-01 9.46045073e-01 1.88533268e-01]
 [0.00000000e+00 2.52753166e-01 9.14213579e-01 3.16748116e-01]
 [2.14415552e-03 5.72489525e-02 1.56523353e-01 9.86011359e-01]
 [0.00000000e+00 1.33127727e-02 1.95873713e-02 9.99719513e-01]
 [0.00000000e+00 2.30514111e-01 8.20473954e-01 5.23149821e-01]
 [2.15755616e-03 8.04768446e-02 1.27295813e-01 9.88592231e-01]
 [0.00000000e+00 2.61184711e-01 9.37586140e-01 2.29596987e-01]
 [5.47073490e-04 1.75610590e-02 4.43129527e-02 9.98863190e-01]
 [0.00000000e+00 2.10315013e-01 7.48578858e-01 6.28806241e-01]
 [0.00000000e+00 2.76253453e-01 7.62789385e-01 5.84667755e-01]
 [1.64405537e-03 6.00080212e-02 7.56265472e-02 9.953275

In [15]:
model = SVC(kernel='linear', C=1E10)

In [16]:
model.fit(xtrain, ytrain)

SVC(C=10000000000.0, kernel='linear')

In [17]:
predictions = model.predict(xtest)
print(predictions)

[0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0
 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 1 1
 1]


In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [19]:
percentage = accuracy_score(ytest,predictions)

In [20]:
res = confusion_matrix(ytest, predictions)
print(classification_report(ytest,predictions))
print("Confusion Matrix")
print(res)
print(f"Test Set: {len(xtest)}")
print(f"Accuracy = {percentage*100} %")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       1.00      1.00      1.00        22

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75

Confusion Matrix
[[53  0]
 [ 0 22]]
Test Set: 75
Accuracy = 100.0 %
